language: android
jdk: oraclejdk8

android:
    components:
      - tools
      - platform-tools
      - tools
      - build-tools-23.0.3
      - android-23
    licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
script:
   - ./gradlew build
before_install:
   - chmod +x gradlew
  
branches:
    only:
        - master
